# Generated by Django 4.2.14 on 2024-07-13 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_categories_options_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='characters',
        ),
    ]
