# Generated by Django 4.2.14 on 2024-07-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_categories_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
